forge "http://forge.puppetlabs.com"

mod "puppetlabs/apt", "1.4.0"
mod "maestrodev/maven", "1.2.1"
mod "rtyler/jenkins", "1.0.0"
mod "hubspot/nexus", "1.2.0"
mod "maestrodev/sonarqube", "2.1.2"
mod "puppetlabs/apache", "1.1.1"
